services:
  app:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_DATABASE_URI=$MONGO_DATABASE_URI
      - MONGO_DATABASE_NAME=$MONGO_DATABASE_NAME
      - MONGO_BIOMETRICS_DATABASE_NAME=$MONGO_BIOMETRICS_DATABASE_NAME
      - ENVIRONMENT=$ENVIRONMENT
      - FLASK_DEBUG= 1
    volumes:
      - .:/src

  mongo:
    image: mongo:latest
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
